#!/usr/bin/env python3

import argparse
import csv
import logging
from logging.handlers import RotatingFileHandler
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

DOCKER_BACKUP_IMAGE = "offen/docker-volume-backup:v2"

@dataclass(frozen=True)
class BackupJob:
    container: str
    volumes: list[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Back up docker volumes to S3")
    parser.add_argument("--volumes", default="backup-volumes.csv", help="Path to volume CSV")
    parser.add_argument("--env-file", default="backup.env", help="Path to env file with AWS secrets")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print actions without stopping containers or running backups",
    )
    return parser.parse_args()


def setup_logging(level: str, log_file: Path = Path("backup.log")) -> None:
    root = logging.getLogger()
    root.setLevel(getattr(logging, level))
    root.handlers.clear()

    formatter = logging.Formatter("%(asctime)s %(levelname)s %(message)s")

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    root.addHandler(console_handler)

    file_handler = RotatingFileHandler(
        log_file,
        maxBytes=100000,    # Maximum size of a log file in bytes before rotation
        backupCount=3       # Number of backup files to keep
    )
    file_handler.setLevel("ERROR")
    file_handler.setFormatter(formatter)
    root.addHandler(file_handler)

def run(cmd: list[str], check: bool = True, dry_run: bool = False) -> subprocess.CompletedProcess[str]:
    logging.debug("$ %s", " ".join(cmd))
    if dry_run:
        return subprocess.CompletedProcess(cmd, 0, "", "")
    return subprocess.run(cmd, check=check, text=True, capture_output=True)

# === CHECKS
def docker_available(dry_run: bool) -> bool:
    try:
        run(["docker", "version"], dry_run=dry_run)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False

def docker_container_exists(name: str, dry_run: bool = False) -> bool:
    if dry_run:
        return True
    result = run(["docker", "container", "inspect", name], check=False)
    return result.returncode == 0


def docker_volume_exists(name: str, dry_run: bool = False) -> bool:
    if dry_run:
        return True
    result = run(["docker", "volume", "inspect", name], check=False)
    return result.returncode == 0


def is_container_running(name: str, dry_run: bool = False) -> bool:
    if dry_run:
        return True
    result = run(
        ["docker", "inspect", "-f", "{{.State.Running}}", name],
        check=False,
    )
    return result.returncode == 0 and result.stdout.strip() == "true"


def stop_container(name: str, dry_run: bool = False) -> None:
    logging.info("Stopping container %s", name)
    run(["docker", "stop", name], dry_run=dry_run)


def start_container(name: str, dry_run: bool = False) -> None:
    logging.info("Starting container %s", name)
    run(["docker", "start", name], dry_run=dry_run)


# === LOGIC
def build_backup_filename(volume: str) -> str:
    # The timestamp is generated by the backup container
    return f"{volume}-%Y-%m-%dT%H-%M-%S.tar.gz"


def run_backup(container: str, volume: str, env_file: Path, dry_run: bool = False) -> None:
    backup_filename = build_backup_filename(volume)
    logging.info(
        "Backing up volume %s (container=%s, s3_path=%s, filename=%s)",
        volume,
        f"{container}/{volume}",
        container,
        backup_filename,
    )
    cmd = [
        "docker", "run", "--rm",
        "-v", f"{volume}:/backup/data",
        "--env-file", str(env_file),
        "-e", f"AWS_S3_PATH={container}/{volume}",
        "-e", f"BACKUP_FILENAME={backup_filename}",
        "-e", f"BACKUP_PRUNING_PREFIX={volume}",
        "--entrypoint",
        "backup",
        DOCKER_BACKUP_IMAGE,
    ]
    run(cmd, dry_run=dry_run)


def parse_jobs(csv_path: Path) -> list[BackupJob]:
    jobs: list[BackupJob] = []

    with csv_path.open(newline="") as f:
        reader = csv.DictReader(f)
        expected_fields = {"enabled", "container", "volumes"}
        if not reader.fieldnames or set(reader.fieldnames) != expected_fields:
            raise ValueError(
                "Invalid CSV header. Expected exactly: enabled,container,volumes"
            )

        for row in reader:
            if row["enabled"] != "1":
                continue

            container = row["container"].strip()
            volumes = [part.strip() for part in row["volumes"].split(";") if part.strip()]

            if not container:
                raise ValueError("Container name cannot be empty for enabled rows")
            if not volumes:
                raise ValueError(f"No volumes provided for enabled container: {container}")

            jobs.append(BackupJob(container=container, volumes=volumes))

    return jobs


def backup_container_group(
    container: str,
    volumes: list[str],
    env_file: Path,
    dry_run: bool = False,
) -> bool:
    success = True

    if not docker_container_exists(container, dry_run=dry_run):
        logging.error(
            "step=validate container=%s error=Container does not exist",
            container,
        )
        return False

    for volume in volumes:
        if not docker_volume_exists(volume, dry_run=dry_run):
            logging.error(
                "step=validate container=%s volume=%s error=Volume does not exist",
                container,
                volume,
            )
            success = False

    if not success:
        return False

    stopped = False
    try:
        try:
            stop_container(container, dry_run=dry_run)
        except subprocess.CalledProcessError as exc:
            error_detail = exc.stderr.strip() if exc.stderr else str(exc)
            logging.error(
                "step=stop container=%s error=%s",
                container,
                error_detail,
            )
            return False

        stopped = True

        for volume in volumes:
            try:
                run_backup(container, volume, env_file=env_file, dry_run=dry_run)
            except subprocess.CalledProcessError as exc:
                error_detail = exc.stderr.strip() if exc.stderr else str(exc)
                logging.error(
                    "step=backup container=%s volume=%s error=%s",
                    container,
                    volume,
                    error_detail,
                )
                success = False
    finally:
        if stopped:
            try:
                start_container(container, dry_run=dry_run)
                if not is_container_running(container, dry_run=dry_run):
                    logging.error(
                        "step=health-check container=%s error=Container did not return to running state",
                        container,
                    )
                    success = False
            except subprocess.CalledProcessError as exc:
                error_detail = exc.stderr.strip() if exc.stderr else str(exc)
                logging.error(
                    "step=start container=%s error=%s",
                    container,
                    error_detail,
                )
                success = False

    return success


def main():
    args = parse_args()
    setup_logging("INFO")

    jobs_path = Path(args.volumes)
    env_file_path = Path(args.env_file)

    if not docker_available(dry_run=args.dry_run):
        logging.error("Docker is not available")
        sys.exit(2)

    if not jobs_path.exists():
        logging.error("Jobs file not found: %s", jobs_path)
        sys.exit(2)

    if not env_file_path.exists():
        logging.error("Env file not found: %s", env_file_path)
        sys.exit(2)

    try:
        jobs = parse_jobs(jobs_path)
    except ValueError as exc:
        logging.error("%s", exc)
        sys.exit(2)

    if not jobs:
        logging.warning("No enabled volumes found in %s", jobs_path)

    had_errors = False
    for job in jobs:
        logging.info("Processing container %s (%d volume(s))", job.container, len(job.volumes))
        ok = backup_container_group(
            job.container,
            job.volumes,
            env_file_path,
            dry_run=args.dry_run,
        )
        if not ok:
            had_errors = True

    if had_errors:
        logging.error("Backup finished with errors. See backup.log for details.")
        sys.exit(1)

    logging.info("All backups completed successfully")


if __name__ == "__main__":
    main()
