services:
  # === NGINX - 80, 443
  proxy:
    image: nginx
    container_name: proxy
    networks:
      - proxy_network
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: bind
        source: nginx
        target: /etc/nginx/conf.d/
      # - certs:/etc/nginx/certs

  # === MEDIA SERVER - 8000
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8000:8096/tcp # for devices, that block local dns
      - 7359:7359/udp
    networks:
      - proxy_network
    volumes:
      - type: bind
        source: jellyfin/config
        target: /config
      - jellyfin-cache:/cache
      - type: bind
        source: jellyfin/media
        target: /media
    restart: 'unless-stopped'

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    # ports:
    #   - 8000:80/tcp
    networks:
      - proxy_network
    volumes:
      - type: bind
        source: jellyfin/media
        target: /srv
      - filebrowser-database:/database
      - filebrowser-config:/config
    restart: 'unless-stopped'

  # === KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak
    depends_on:
      - keycloak-db
    # ports:
    #   - "8080:8080"
    networks:
     - proxy_network
     - keycloak-network
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
    env_file: keycloak.env
    command: "start-dev"

  keycloak-db:
    image: postgres:17
    container_name: keycloak-db
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    env_file: keycloak.env
    networks:
     - keycloak-network

  # === KUMA
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    # ports:
    #   - "3001:3001"
    networks:
     - proxy_network
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped

  # === PIHOLE - 53
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
     - proxy_network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env_file: pihole.env
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - pihole-data:/etc/pihole
      - type: bind
        source: pihole/pihole.toml
        target: /etc/pihole/pihole.toml
    restart: unless-stopped

volumes:
  jellyfin-cache:

  filebrowser-data:
  filebrowser-database:
  filebrowser-config:

  keycloak-data:

  uptime-kuma-data:

  pihole-data:

networks:
  keycloak-network:

  proxy_network:
