services:
  # === MEDIA SERVER - 8000, 8004
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - 8000:8096/tcp
      - 7359:7359/udp
    volumes:
      - jellyfish-config:/config
      - jellyfish-cache:/cache
      - type: bind
        source: jellyfish/media
        target: /media
    restart: 'unless-stopped'

  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 8004:80/tcp
    volumes:
      - type: bind
        source: jellyfish/media
        target: /srv
      - filebrowser-database:/database
      - filebrowser-config:/config
    restart: 'unless-stopped'

  # === KEYCLOAK - 8002
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    ports:
      - "8002:8080"
    networks:
     - keycloak-network
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
    env_file: keycloak.env
    command: "start-dev"

  keycloak-db:
    image: postgres:17
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    env_file: keycloak.env
    networks:
     - keycloak-network

  # === KUMA - 8003
  uptime-kuma:
    image: louislam/uptime-kuma:2
    ports:
      - "8003:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped

  # === PIHOLE - 53, 8001
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8001:80/tcp"
      # - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_api_password: 'pihole'
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_dns_upstreams: '9.9.9.9;8.8.8.8'
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - pihole-data:/etc/pihole
    restart: unless-stopped

volumes:
  jellyfish-config:
  jellyfish-cache:

  filebrowser-data:
  filebrowser-database:
  filebrowser-config:

  keycloak-data:

  uptime-kuma-data:

  pihole-data:

networks:
  keycloak-network:
