services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.3
    container_name: homepage
    env_file:
      - homepage/homepage.env
    volumes:
      - type: bind
        source: homepage/config
        target: /app/config
    networks:
      - proxy
    environment:
      HOMEPAGE_ALLOWED_HOSTS: tira-misu.org
      PUID: 1000
      PGID: 1000
    restart: 'unless-stopped'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`tira-misu.org`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"


  # === TRAEFIK - 80, 443
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    command:
      # Healthcheck
      - "--ping=true"

      - "--entrypoints.web.address=:80"
      # Redirect to https
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.filename=/tls/tls.yaml"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=pi-compose_proxy"

      # API & Dashboard 
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability 
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`traefik.tira-misu.org`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$AhREzA4N$$DuoI0Izq25uTA/UBPEov70"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/certs:ro
      - type: bind
        source: traefik/tls.yaml
        target: /tls/tls.yaml
        read_only: true
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # === MEDIA SERVER STACK
  # Media Server
  jellyfin:
    image: jellyfin/jellyfin:10.11
    container_name: jellyfin
    ports:
      # - 8096:8096/tcp
      - 7359:7359/udp # discovery in local network
    networks:
      - proxy
    volumes:
      # - type: bind
      #   source: jellyfin/config
      #   target: /config
      - jellyfin-config:/config # plugins, watch history
      - jellyfin-backup:/config/data/backups # plugins, watch history
      - jellyfin-cache:/cache
      - type: bind
        source: jellyfin/media
        target: /media
        read_only: true
      # branding (could be done with entrypoint script but this is easier to change
      - type: bind
        source: jellyfin/branding/branding.xml
        target: /config/config/branding.xml
      - type: bind
        source: jellyfin/branding/icon-transparent.baba78f2a106d9baee83.png
        target: /jellyfin/jellyfin-web/icon-transparent.baba78f2a106d9baee83.png
        read_only: true
      - type: bind
        source: jellyfin/branding/banner-light.b113d4d1c6c07fcb73f0.png
        target: /jellyfin/jellyfin-web/banner-light.b113d4d1c6c07fcb73f0.png
        read_only: true
      - type: bind
        source: jellyfin/branding/favicon.bc8d51405ec040305a87.ico
        target: /jellyfin/jellyfin-web/favicon.bc8d51405ec040305a87.ico
        read_only: true
      - type: bind
        source: jellyfin/branding/touchicon144.39209dd2362c0db7c673.png
        target: /jellyfin/jellyfin-web/touchicon144.39209dd2362c0db7c673.png
        read_only: true
      - type: bind
        source: jellyfin/branding/favicons
        target: /jellyfin/jellyfin-web/favicons
        read_only: true
    restart: 'unless-stopped'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`media.tira-misu.org`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"

  seerr:
    image: ghcr.io/seerr-team/seerr:v3.2.0
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Berlin
    volumes:
      - seerr-config:/app/config
    # ports:
    #   - 5055:5055
    networks:
      - proxy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seerr.rule=Host(`discovery.tira-misu.org`)"
      - "traefik.http.services.seerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.seerr.entrypoints=websecure"
      - "traefik.http.routers.seerr.tls=true"


  filebrowser:
    image: filebrowser/filebrowser:v2.63.2
    container_name: filebrowser
    # ports:
    #   - 80:80/tcp
    networks:
      - proxy
    volumes:
      - type: bind
        source: jellyfin/media
        target: /srv
      - filebrowser-data:/database
      - filebrowser-config:/config
    restart: 'unless-stopped'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.tira-misu.org`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"

  # === KUMA
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    # ports:
    #   - "3001:3001"
    networks:
     - proxy
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`kuma.tira-misu.org`)"
      - "traefik.http.routers.kuma.entrypoints=websecure"
      - "traefik.http.routers.kuma.tls=true"

  # === PIHOLE
  pihole:
    image: pihole/pihole:2026.04.1
    container_name: pihole
    networks:
     - proxy
    ports:
      # - "80:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    env_file: pihole/pihole.env
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - pihole-data:/etc/pihole
      - type: bind
        source: pihole/pihole.toml
        target: /etc/pihole/pihole.toml
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`dns.tira-misu.org`)"

       # Redirect / to /admin
      - "traefik.http.routers.pihole.middlewares=pihole-redirect"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^https://dns.tira-misu.org/$"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=https://dns.tira-misu.org/admin"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.permanent=true" 

      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"

  # === RATHOLE - Wireguard
  rathole:
    image: ghcr.io/rathole-org/rathole:dev
    container_name: rathole
    network_mode: host
    volumes:
      - type: bind
        source: rathole/client.toml
        target: /app/config.toml
    restart: unless-stopped
    entrypoint: "./rathole --client /app/config.toml"

  acme-sh:
    image: neilpang/acme.sh:3.1.3
    container_name: acme.sh
    volumes:
      - certs:/acme.sh
      - type: bind
        source: acme/entrypoint.sh
        target: /setup.sh
    entrypoint: ["/bin/sh", "-c", "./setup.sh"]
    env_file: "acme/acme.env"
    stdin_open: true
    tty: true
    restart: no

volumes:
  jellyfin-cache:
  jellyfin-config:
  jellyfin-backup:

  filebrowser-data:
  filebrowser-config:

  seerr-config:

  uptime-kuma-data:

  pihole-data:

  certs:

networks:
  proxy:
