services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - 8000:8096/tcp
      - 7359:7359/udp
    volumes:
      - jellyfish-config:/config
      - jellyfish-cache:/cache
      - type: bind
        source: media
        target: /media
    restart: 'unless-stopped'

  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 8004:80/tcp
    volumes:
      - type: bind
        source: media
        target: /srv
      - filebrowser-database:/database
      - filebrowser-config:/config
    restart: 'unless-stopped'

volumes:
  jellyfish-config:
  jellyfish-cache:

  filebrowser-data:
  filebrowser-database:
  filebrowser-config:
