services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - 8000:8096/tcp
      - 7359:7359/udp
    volumes:
      - type: bind
        source: media
        target: /media
    restart: 'unless-stopped'

