[dns]
    hosts = [
        "192.168.178.60 tira-misu.org",
        "192.168.178.60 media.tira-misu.org",
        "192.168.178.60 dns.tira-misu.org",
        "192.168.178.60 filebrowser.tira-misu.org",
        "192.168.178.60 kuma.tira-misu.org",
        "192.168.178.60 traefik.tira-misu.org",
    ]
    listeningMode = "ALL"
    upstreams = ["9.9.9.9", "8.8.8.8"]
