[dns]
    hosts = [
        # tira-misu.org
        "192.168.178.60 tira-misu.org",
        "fe80::f75d:30d2:4fdd:529c tira-misu.org",

        # media.tira-misu.org
        "192.168.178.60 media.tira-misu.org",
        "fe80::f75d:30d2:4fdd:529c media.tira-misu.org",

        # dns.tira-misu.org
        "192.168.178.60 dns.tira-misu.org",
        "fe80::f75d:30d2:4fdd:529c dns.tira-misu.org",

        # filebrowser.tira-misu.org
        "192.168.178.60 filebrowser.tira-misu.org",
        "fe80::f75d:30d2:4fdd:529c filebrowser.tira-misu.org",

        # kuma.tira-misu.org
        "192.168.178.60 kuma.tira-misu.org",
        "fe80::f75d:30d2:4fdd:529c kuma.tira-misu.org",

        # id.tira-misu.org
        "192.168.178.60 id.tira-misu.org",
        "fe80::f75d:30d2:4fdd:529c id.tira-misu.org",
    ]
    listeningMode = "ALL"
    upstreams = ["9.9.9.9", "8.8.8.8"]
