---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Niclasflix:
        icon: netflix.png
        href: https://media.tira-misu.org
        description: Medienserver
        widget:
          version: 1
          type: jellyfin
          url: http://jellyfin:8096
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
          enableBlocks: true
          enableNowPlaying: true
          enableUser: true
          enableMediaControl: false
          showEpisodeNumber: false
          expandOneStreamToTwoRows: false

    - Discovery:
        icon: overseerr.png
        href: https://discovery.tira-misu.org
        description: |
          Filme und Serien Anfragen 
          Für direktes herunterladen direkt das Filme oder Serien Widget verwenden.
        widget:
          type: seerr
          url: http://seerr:5055
          key: "{{HOMEPAGE_VAR_SEERR_API_KEY}}"

    - Filebrowser:
        icon: filebrowser.png
        href: https://filebrowser.tira-misu.org
        description: Mediendateien verwalten
        widget:
          type: filebrowser
          url: http://filebrowser
          username: "{{HOMEPAGE_VAR_FILEBROWSER_USERNAME}}"
          password: "{{HOMEPAGE_VAR_FILEBROWSER_PASSWORD}}"

    - Filme:
        icon: radarr.png
        href: https://movies.tira-misu.org
        description: Automatisches Herunterladen von Filmen

    - Serien:
        icon: sonarr.png
        href: https://shows.tira-misu.org
        description: Automatisches Herunterladen von Serien und Anime


    - Download Client:
        icon: sabnzbd.png
        href: https://download.tira-misu.org
        description: Downloads verwalten

- Admin:
    - Traefik:
        icon: traefik.png
        href: https://traefik.tira-misu.org
        description: Reverse Proxy Dashboard

    - VPN Uptime:
        icon: uptime-kuma.png
        href: https://kuma.tira-misu.org
        widget:
          type: uptimekuma
          url: http://uptime-kuma:3001
          slug: vpn

    - Pi-hole Admin:
        icon: pi-hole.png
        href: https://dns.tira-misu.org
        description: DNS und Ad-Blocker
        widget:
          type: pihole
          url: http://pihole
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_PASSWORD}}"

    - Prowlarr:
        icon: prowlarr.png
        href: https://index.tira-misu.org
        description: Zentrale Verwaltung von Indexern für Serien und Filme
